#!/usr/bin/env node
/**
 * Slice the hero tour MP4 into per-module short clips (Tier 2) — one short per
 * tour step, each its own narrated segment + moving spotlight. Far more robust
 * + consistent than bespoke per-module click scripts.
 *
 * Reads assets/module-clips.json: [{ name, src, start, dur }]
 *   name  — output basename → assets/videos/module-<name>.mp4
 *   src   — source mp4 (the hero tour)
 *   start — seconds into the hero where this module's step begins
 *   dur   — clip length in seconds
 *
 * Re-encodes the segment (clean cut on keyframe boundaries, audio intact).
 * module-clips.json is generated by record-hero.mjs from the per-step offsets,
 * or hand-edited.
 *
 * Usage: node .jez/scripts/slice-modules.mjs [name]
 */
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../..')
const CLIPS = path.join(ROOT, 'assets/module-clips.json')
const OUT_DIR = path.join(ROOT, 'assets/videos')
fs.mkdirSync(OUT_DIR, { recursive: true })

if (!fs.existsSync(CLIPS)) {
  console.error(`No clip specs at ${CLIPS}. Generated by the recorder, or hand-write [{name,src,start,dur}].`)
  process.exit(1)
}
const clips = JSON.parse(fs.readFileSync(CLIPS, 'utf8'))
const pick = process.argv[2]
const selected = pick ? clips.filter((c) => c.name === pick) : clips

console.log(`slicing ${selected.length} module short(s)…`)
for (const { name, src, start, dur } of selected) {
  const srcPath = path.isAbsolute(src) ? src : path.join(ROOT, src)
  if (!fs.existsSync(srcPath)) {
    console.warn(`  SKIP ${name}: source missing (${src})`)
    continue
  }
  const out = path.join(OUT_DIR, `module-${name}.mp4`)
  execFileSync('ffmpeg', [
    '-y', '-ss', String(start), '-t', String(dur), '-i', srcPath,
    '-c:v', 'libx264', '-preset', 'fast', '-crf', '20', '-pix_fmt', 'yuv420p',
    '-c:a', 'aac', '-b:a', '128k', '-movflags', '+faststart',
    out,
  ], { stdio: 'pipe' })
  const mb = (fs.statSync(out).size / 1024 / 1024).toFixed(1)
  console.log(`  module-${name}.mp4  ${start}s +${dur}s  ${mb}MB`)
}
console.log('done — assets/videos/module-*.mp4')
