-- Add conversation summary + starred fields.
-- Auth tables were regenerated by drizzle-kit due to drift with better-auth's
-- manually-applied schema; those diffs are stripped from this migration so we
-- only touch `conversations`.
ALTER TABLE `conversations` ADD `summary` text;--> statement-breakpoint
ALTER TABLE `conversations` ADD `starred` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
CREATE INDEX `conversations_user_starred_idx` ON `conversations` (`user_id`,`starred`,`updated_at`);
