// GENERATED by .jez/scripts/gen-tour-audio.py — do not edit by hand.
// Spotlight cue timings: each entry moves the halo to `selector` when the
// step narration reaches `at` seconds. Regenerate whenever scripts change.
export interface TourCue {
  selector: string
  at: number
}

export const TOUR_CUES: Record<string, TourCue[]> = {
  "step-1": [
    {
      "selector": "[data-tour=\"home-welcome\"]",
      "at": 0.0
    },
    {
      "selector": "[data-tour=\"home-panels\"]",
      "at": 7.87
    },
    {
      "selector": "[data-tour=\"home-actions\"]",
      "at": 16.31
    }
  ],
  "step-2": [
    {
      "selector": "[data-tour=\"chat-input\"]",
      "at": 0.0
    }
  ],
  "step-3": [
    {
      "selector": "[data-tour=\"skills-list\"]",
      "at": 0.0
    }
  ],
  "step-4": [
    {
      "selector": "[data-tour=\"knowledge-list\"]",
      "at": 0.0
    }
  ],
  "step-5": [
    {
      "selector": "[data-tour=\"inbox-list\"]",
      "at": 0.0
    }
  ],
  "step-6": [
    {
      "selector": "[data-tour=\"projects-list\"]",
      "at": 0.0
    }
  ],
  "step-7": [
    {
      "selector": "[data-tour=\"routines-list\"]",
      "at": 0.0
    }
  ],
  "step-8": [
    {
      "selector": "[data-tour=\"agents-list\"]",
      "at": 0.0
    }
  ],
  "step-9": [
    {
      "selector": "[data-tour=\"activity-list\"]",
      "at": 0.0
    }
  ],
  "step-10": [
    {
      "selector": "[data-tour=\"connections-list\"]",
      "at": 0.0
    }
  ],
  "step-11": [
    {
      "selector": "[data-tour=\"files-list\"]",
      "at": 0.0
    }
  ],
  "step-12": [
    {
      "selector": "[data-tour=\"org-members\"]",
      "at": 0.0
    }
  ],
  "step-13": [
    {
      "selector": "[data-tour=\"settings-tabs\"]",
      "at": 0.0
    }
  ]
}
